enableTelemetry: false

nodeLinker: node-modules

supportedArchitectures:
  os:
  - "darwin"
  cpu:
  - "arm"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
