name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  # release:
  #   name: Release beta
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Install
  #       uses: ./.github/actions/install

  #     - name: Publish Beta
  #       run: yarn release:beta --ci
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-18.04
    # needs: release

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ github.token }}"
          prerelease: false
