name: Release

on:
  push:
    paths-ignore:
      - 'assets/**'
      - '.vscode/**'
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Check
        run: yarn check

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test

      - name: Build Site
        shell: bash
        run: |
          yarn --cwd apps/site ci:build

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./apps/site/out
          cname: tamagui.dev

      # test this later...
      # - name: Publish Beta
      #   run: yarn release:beta --ci
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
